docs/installation.rst, extension/AdcCore.py, scripts/upload_core.py, setup.py
There was an issue properly replacing the linux binaries shipped with with the downloaded MacOS binaries. This should be fixed by this PR. I have made a test upload with the proposed fix at <https://get.adc-connect.org/adcc-0.13.1.tar.gz>.
@maxscheurer Could you test that?
=> Bugfix for MacOS installs from pip

setup.py
Dependencies are now declared without parentheses around the version as specified [here](https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-dependencies).
This will keep us out of trouble when going for conda packaging.
=> Canonically declaring dependencies in setup.py

.travis.yml, docs/developers.rst, docs/installation.rst, extension/AdcCore.py
This allows adcc developers with adccore access to dump a json config in their home, which configures once and for all the location of adccore. This way automatic checkouts of adccore are possible. The syntax of the json file is explained in the documentation.
=> Autocheckout of adccore

extension/export_MoSpaces.cc, extension/export_ReferenceState.cc
The `to_ctx` functions are currently not needed and dropping them allows to transparently restructure adccore with respect to the CtxMap functionality without breaking the interface to adcc.
=> Drop exporting ctx symbols

.travis.yml, adcc/backends/available_backends.py, docs/installation.rst, extension/convert_timer.cc, extension/export_CachingPolicy.cc, extension/export_HartreeFockProvider.cc, extension/export_MoSpaces.cc, extension/export_OneParticleOperator.cc, extension/export_ReferenceState.cc, extension/export_Symmetry.cc, extension/export_Tensor.cc, setup.py
This PR will add support for `clang`, which will be beneficial for `conda` deployment.
=> [WIP] Clang support

docs/developers.rst, extension/AdcCore.py
I tried it with a locally built numpy, linked to MKL. I did not try it with conda, but I leave that to @maxscheurer  :smile:.
Closes #16.
=> Detect and honour an MKL numpy when building adccore

adcc/ExcitedStates.py
Print the transition dipole moments in `describe()` instead of state dipole moments 😄
=> Correctly print transition dipole moments

adcc/AdcBlockView.py, adcc/AdcMatrix.py, adcc/ExcitedStates.py, adcc/MoSpaces.py, adcc/__init__.py, adcc/guess.py, adcc/solver/davidson.py, adcc/solver/preconditioner.py, adcc/test_AdcBlockView.py, adcc/test_AdcMatrix.py, adcc/test_workflow.py, adcc/workflow.py, extension/export_AdcMatrix.cc, extension/export_OneParticleOperator.cc, setup.cfg
Datastructure to transparently view only the singles or doubles block of a bigger ADC matrix. Works with the Jacobi-Davidson. Others have not been tested, but should work as well.
Does not work for the doubles part because right now AmplitudeVector assumes that the first block is the singles block (and if we zoom into doubles only than the first block is the doubles block). I'll not attempt to cure that for now, but just to keep that in mind.
Tests are coming ...
=> ADC matrix blockview

environment.yml
We use the development versions of psi4 and adcc from conda. Closes #46.
=> Update config for binder

conda/meta.yaml.in
Some suggestions to hopefully solve https://github.com/psi4/psi4/pull/1848.
- Output of failing run on Azure: https://dev.azure.com/psi4/psi4/_build/results?buildId=1779&view=logs&j=96451287-da82-57a8-2c11-8da7db9ab71a&t=41b51342-9bfb-52c2-7efb-0050141a3f7e
My rationale for the change:
- We need HDF5 only via h5py. Any version of h5py above the specified boundary should be good. No need to pin.
- Same for tiqn, matplotlib, scipy.
- HDF5 now pinned to a version compatible with chemps2
Any other suggestions?
=> Conda suggestions

MANIFEST.in, extension/AdcCore.py
Doesn’t work with Conda anyway and for the adccore binaries we build with such an old version of glibc and libstdc++ that basically all relevant Debian and Ubuntu OSes are directly supported.
=> Stop installing stdlib

.travis.yml
Since `pyscf` 1.7.3 was pushed to `pip` two days ago, the CI should work again with PE.
Closes #72
=> Install CPPE directly from pip

.travis.yml
To reach consistency with the build setup for `adccore`, this PR downgrades XCode on macOS to `10.2`.
=> Downgrade 10.14 XCode version in CI

adcc/memory_pool.py
Extend documentation of `memory_pool` to clearify #86 .
=> Extend documentation of `memory_pool`.

docs/calculations.rst
Outdated name `state.eigenvectors` renamed to `state.excitation_vector` (reported by Marvin, thanks!)
=> Fix error in Docs

adcc/ExcitedStates.py, adcc/LazyMp.py, adcc/ReferenceState.py
Adding to_qcvars function, which could serve https://github.com/MolSSI/QCEngine/pull/277.
Actually getting this to be useful for Psi4 is not so easy, so I would not bother, but this poses the question why to even have this function in the first place at it might be pretty specific to QCEngine. On the other hand this allows us to add new properties to adcc and make them available to QCEngine without the need to modify code in that repo all the time, which is probably easier to maintain.
@maxscheurer Thoughts?
=> Implement to_qcvars function

.github/workflows/ci.yaml, adcc/HfCounterData.py, adcc/test_Tensor.py, libadcc/TensorImpl.cc, setup.py
**Note:** Coverage drops because previously the coverage of the C++ test files themselves was also reported, which does not make that much sense in my opinion.
=> Various small fixes

.github/workflows/ci.yaml, adcc/AmplitudeVector.py, adcc/test_AmplitudeVector.py
This PR fixes some weird behavior of the `AmplitudeVector` and coveralls upload.
`__setattr__` is now forwarded to `__setitem__`, in analogy to `__getattr__`
Test that would hit the previous error added. I'd vote for a `0.15.7` release after this fix, because this is a serious bug...
=> Fix AmplitudeVector and coveralls

.github/workflows/ci.yaml, adcc/conftest.py, adcc/memory_pool.py, conda/meta.yaml.in, libadcc/AdcMemory.cc, libadcc/AdcMemory.hh, libadcc/MoSpaces.cc, libadcc/Symmetry.cc, libadcc/TensorImpl.hh, libadcc/pyiface/export_AdcMemory.cc, libadcc/tests/MoIndexTranslationTest.cc, libadcc/tests/MoSpacesTest.cc, setup.py
Needs the changes from https://github.com/adc-connect/libtensor/pull/9.
@maxscheurer Feel free to play with it with a nice example. Libxm seems to write everything to disk and prefetch as it goes. That means that the memory requirement is super small, but also that it's only worth it if you have a fast disk and a calculation that no longer fits into your available RAM. But in that sense it closes a gap that adcc still has.
=> Adapt AdcMemory for libxm

adcc/OperatorIntegrals.py, adcc/backends/pyscf.py, adcc/backends/test_backends_pcm.py, adcc/testdata/generate_psi4_data.py, adcc/testdata/generate_pyscf_data.py, adcc/testdata/psi4_dump.yml, adcc/testdata/pyscf_dump.yml
In #132, `pyscf` backend does not work anymore when `cppe` is not present because of top-level module import.
This also got past me during code review 😄
=> Fix bug with pyscf module import

adcc/adc_pp/matrix.py
This is needed to avoid running into a non-implemented contraction.
=> Avoid overly smart opteinsum

.github/workflows/ci.yaml, adcc/backends/test_backends_pcm.py, setup.py
=> Fix `setuptools`

.github/workflows/ci.yaml, .github/workflows/publish.yaml, adcc/AdcMatrix.py, adcc/AmplitudeVector.py, adcc/ExcitedStates.py, adcc/IsrMatrix.py, adcc/OneParticleOperator.py, adcc/__init__.py, adcc/adc_pp/util.py, adcc/backends/test_backends_pcm.py, adcc/functions.py, adcc/solver/explicit_symmetrisation.py, adcc/solver/test_power_method.py, conda/environment.yml, docs/developers.rst
As announced, this removes the old way of defining/accessing matrix/vector blocks (i.e. vec['s'] and so on).
Closes #181.
=> Remove old block style and other deprecations

adcc/backends/test_backends_crossref.py, adcc/backends/test_backends_pcm.py
**Changes**
- `adcc/backends/test_backends_crossref.py`: 
As mentioned in Issue #186, test_adc2_r2methyloxirane_ccpvdz used to fail, I increased the convergence criteria to 5e-7, as discussed with @jonasleitner, and now the test passes again. 
- `adcc/backends/test_backends_pcm.py`:
The `cavity.npz` file from the `Psi4` calculation was not removed after the tests. I added it to the files which are removed after the tests in `remove_cavity_psi4`.
=> conv_tol crossref, remove PCM cavity files

.github/workflows/ci.yaml, adcc/solver/SolverStateBase.py, adcc/solver/davidson.py, adcc/tests/backends/backends_crossref_test.py, adcc/tests/functionality_test.py, adcc/tests/solver/davidson_test.py, adcc/workflow.py
This pull request covers several issues related to the Davidson solver:
- The Davidson solver occasionally lost subspace orthogonality, sometimes leading to linear dependence within the subspace, resulting in instant solver convergence towards zero eigenpairs.
With this pull request, subspace orhogonality loss is fixed using a conventional Gram-Schmidt reorthogonalisation in case this is needed, i.e., whenever the vector to be added to the subspace has non-negligible overlap with the previous subspace vectors. This comes at the expense of, at least, computing `n_ss_vec` addtional scalar products in each step, which in small systems may amount up to 5% of the total computational time spent for the Davidson solver. The overhead scales $N^4$, that is, for larger systems, the relative penalty …
=> Fix orthgonality loss in Davidson using Gram-Schmidt reorthogonalisation
