- README.md
- setup.py
Unify strings to double quotes in setup.py and use the README.md to get the detailed info for pypi. Also adds some keywords.
> Unify strings in setup.py

- .coveragerc
- .gitignore
- .travis.yml
- README.md
- adcc/misc.py
- docs/index.rst
- docs/zpublications.rst
- scripts/upload_core.py
- setup.py
- setup_veloxchem.sh
This PR will add coverage recording for the python layer of adcc.
> Extend Travis configuration by coverage recording

- docs/about.rst
- docs/adccore.rst
- docs/calculations.rst
- docs/conf.py
- docs/developers.rst
- docs/hostprograms.rst
- docs/index.rst
- docs/installation.rst
- docs/reference.rst
- docs/theory.rst
- docs/zpublications.rst
> Add edit on github link

- .travis.yml
- setup.py
> Drop python 3.5 support

- .travis.yml
- adcc/__init__.py
- setup.cfg
- setup.py
This PR adds deployment to pypi directly from Travis.
I'd say with this merged we can tag and deploy `0.13.2`.
> Add deployment to pypi

- extension/AdcCore.py
- setup.py
Another lot of small amendments for conda builds.
> Amend setup.py for conda builds

- extension/export_Tensor.cc
- extension/util.cc
- extension/util.hh
While I was on it I also removed some unused functions.
> Ensure set_from_ndarray converts to C-style order

- adcc/AdcMatrix.py
- adcc/AmplitudeVector.py
- adcc/OneParticleOperator.py
- adcc/__init__.py
- adcc/functions.py
- adcc/solver/conjugate_gradient.py
- adcc/solver/davidson.py
- adcc/solver/explicit_symmetrisation.py
- adcc/solver/power_method.py
- adcc/solver/preconditioner.py
- adcc/test_Tensor.py
- adcc/test_contract.py
- adcc/test_direct_sum.py
- examples/water/psi4_ccpvdz_cvs_adc2.py
- extension/AdcCore.py
- extension/export_Tensor.cc
- setup.py
> Lazy Tensor evaluation

- adcc/__init__.py
- adcc/backends/psi4.py
- adcc/backends/test_backends_polembed.py
- adcc/functions.py
- adcc/solver/davidson.py
- extension/export_Tensor.cc
- setup.py
Will need an updated adccore. Fixes the timing regressions observed in #67.
> Fix linear combination regression

- adcc/__init__.py
- adcc/functions.py
- adcc/opt_einsum_integration.py
- adcc/test_Tensor.py
- adcc/test_einsum.py
- conda/meta.yaml.in
- setup.py
- ~~Intermediate sharing~~ (Too ambitious for now)
> Integrate opt_einsum

- .travis.yml
- README.md
- docs/index.rst
> Update Travis to travis-ci.com

- adcc/__init__.py
- adcc/backends/__init__.py
- adcc/backends/psi4.py
- adcc/backends/pyscf.py
- adcc/backends/veloxchem.py
- adcc/exceptions.py
- adcc/hdf5io.py
- adcc/test_workflow.py
- adcc/workflow.py
- conda/meta.yaml.in
- extension/export_HartreeFockProvider.cc
- setup.py
During the parsing stage in run_adc, adcc now throws an InputError as a specialised "ValueError"
> Introduce InputError

- adcc/AdcMatrix.py
- adcc/solver/LanczosIterator.py
- adcc/solver/common.py
- adcc/solver/conjugate_gradient.py
- adcc/solver/davidson.py
- adcc/solver/lanczos.py
- adcc/solver/orthogonaliser.py
- adcc/solver/preconditioner.py
- adcc/solver/test_conjugate_gradient.py
- adcc/solver/test_lanczos.py
- adcc/test_AdcMatrix.py
- adcc/test_workflow.py
- adcc/workflow.py
Less useful for standard ADC use cases, but very useful for debugging and for special applications (e.g. large number of eigenpairs).
> Implementation of Block-Lanczos procedure

- adcc/ElectronicTransition.py
- adcc/ExcitedStates.py
- adcc/State2States.py
- adcc/__init__.py
- adcc/adc_pp/state2state_transition_dm.py
- adcc/adc_pp/state_diffdm.py
- adcc/adc_pp/transition_dm.py
- adcc/adc_pp/util.py
- adcc/test_properties.py
- adcc/test_state_densities.py
- adcc/workflow.py
- docs/calculations.rst
- examples/hydrogen_fluoride/pyscf_631g_sf_adc2.py
- examples/water/tpa.py
Python-side equations for State-to-state transition densities.
- ~~[ ] CVS-ADC (I'm not really in the mood to add this though 😄)~~ ➡️ postpone
> State-to-state transition densities

- adcc/AdcMethod.py
- adcc/ElectronicTransition.py
- adcc/solver/LanczosIterator.py
- adcc/solver/lanczos.py
> Small fixes and modularisation of Lanczos

- docs/installation.rst
> Update docs regarding pip MacOS support

- adcc/testdata/0_download_testdata.sh
> Adapt sha256sums for older versions

- .github/workflows/ci.yaml
- MANIFEST.in
- adcc/test_smoke.py
- conda/environment_dev_linux.yml
- scripts/remove_test_files.sh
- setup.py
Minimal testing of functionality.
> Smoke Tests

- .github/workflows/ci.yaml
- adcc/backends/psi4.py
- adcc/backends/test_backends_crossref.py
- conda/environment_dev_linux.yml
> Try psi4 on Conda CI

- adcc/backends/test_backends_pcm.py
- adcc/testdata/pyscf_dump.yml
- conda/environment_dev_linux.yml
> Regenerate PySCF ddCOSMO/PCM testdata
